name: Node.js CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker Compose stack
        run: docker compose up -d

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci && npm install config

      - name: Run tests
        run: npm test
